[package]
name = "axwemulator-core"
version = "0.1.0"
authors = ["ArcticXWolf"]
edition = "2024"
include = ["**/*.rs", "Cargo.toml"]
rust-version = "1.85"

[dependencies]
femtos = "0.1.1"
thiserror = "2.0.11"
