use axwemulator_core::frontend::input::KeyboardEventKey;

pub fn translate_egui_key_to_frontend_key(egui_key: egui::Key) -> Option<KeyboardEventKey> {
    match egui_key {
        egui::Key::A => Some(KeyboardEventKey::A),
        egui::Key::B => Some(KeyboardEventKey::B),
        egui::Key::C => Some(KeyboardEventKey::C),
        egui::Key::D => Some(KeyboardEventKey::D),
        egui::Key::E => Some(KeyboardEventKey::E),
        egui::Key::F => Some(KeyboardEventKey::F),
        egui::Key::G => Some(KeyboardEventKey::G),
        egui::Key::H => Some(KeyboardEventKey::H),
        egui::Key::I => Some(KeyboardEventKey::I),
        egui::Key::J => Some(KeyboardEventKey::J),
        egui::Key::K => Some(KeyboardEventKey::K),
        egui::Key::L => Some(KeyboardEventKey::L),
        egui::Key::M => Some(KeyboardEventKey::M),
        egui::Key::N => Some(KeyboardEventKey::N),
        egui::Key::O => Some(KeyboardEventKey::O),
        egui::Key::P => Some(KeyboardEventKey::P),
        egui::Key::Q => Some(KeyboardEventKey::Q),
        egui::Key::R => Some(KeyboardEventKey::R),
        egui::Key::S => Some(KeyboardEventKey::S),
        egui::Key::T => Some(KeyboardEventKey::T),
        egui::Key::U => Some(KeyboardEventKey::U),
        egui::Key::V => Some(KeyboardEventKey::V),
        egui::Key::W => Some(KeyboardEventKey::W),
        egui::Key::X => Some(KeyboardEventKey::X),
        egui::Key::Y => Some(KeyboardEventKey::Y),
        egui::Key::Z => Some(KeyboardEventKey::Z),
        egui::Key::Num0 => Some(KeyboardEventKey::Number0),
        egui::Key::Num1 => Some(KeyboardEventKey::Number1),
        egui::Key::Num2 => Some(KeyboardEventKey::Number2),
        egui::Key::Num3 => Some(KeyboardEventKey::Number3),
        egui::Key::Num4 => Some(KeyboardEventKey::Number4),
        egui::Key::Num5 => Some(KeyboardEventKey::Number5),
        egui::Key::Num6 => Some(KeyboardEventKey::Number6),
        egui::Key::Num7 => Some(KeyboardEventKey::Number7),
        egui::Key::Num8 => Some(KeyboardEventKey::Number8),
        egui::Key::Num9 => Some(KeyboardEventKey::Number9),
        _ => None,
    }
}
